# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6d31b7a2711df98a03f4c608d137fd4e2f128e990279a7cea0bbf4dd10e38a504da1e2e27ffd64dc3dde758464502ea1082b14f7e23e7dd93d0d71f45c59014

test:
  secret_key_base: cd20a012885780c5045944b4e6da885f78bdd91a25867769eac9fb21c732d7fca4d49532d212bd356f8587f937f1da9622f69c8eb7543d6f6a8ef83d2afee53f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
